### PR TITLE
Rocky9 5 History Rebuild: kernel-5.14.0-503.19.1.el9_5

### PR DESCRIPTION
**Pull request by PlaidCat**
This is a Kernel Rebuild request, currently the code for this is internal to CIQ, however over the next quarter we do plan to make it publically available.

General Process:
* Download all unprocessed `src.rpm`
* for each src,pm
  * Find all commits in changelog up to last known tag ... in this case `5.14.0-503` 
  * Re-play commits in revese order (oldest in change log to newest) with `git cherry-pick`
  * After replay replace ENTIRE code in branch with `rpmbuild -bp` from corresponding src.rpm.
  * Tag Rebuild branch
* Do local build with https://github.com/ctrliq/kernel-src-tree/wiki/Kernel-Make,-KABI,-Install,-and-Reboot-script

Contains the following: http://dl.rockylinux.org/vault/rocky/9.5/BaseOS/source/tree/Packages/k/
* kernel-5.14.0-503.19.1.el9_5 (not yet published to vault but coming)

```
[maple@r9-sigcloud-builder kernel-src-tree]$ ../kernel-tools/kernel_build.sh
/mnt/code/kernel-src-tree
  CLEAN   arch/x86/boot/compressed

  CLEAN   scripts/selinux/mdp
  CLEAN   scripts
  CLEAN   include/config include/generated arch/x86/include/generated .config .config.old .version Module.symvers certs/signing_key.pem certs/signing_key.x509 certs/x509.genkey
[TIMER]{MRPROPER}: 8s
x86_64 architecture detected, copying config
'configs/kernel-x86_64-rhel.config' -> '.config'

[SNIP]

  BTF [M] sound/xen/snd_xen_front.ko
[TIMER]{BUILD}: 1642s
Making Modules
  INSTALL /lib/modules/5.14.0-rocky9_5_rebuild+/kernel/arch/x86/crypto/blake2s-x86_64.ko
  STRIP   /lib/modules/5.14.0-rocky9_5_rebuild+/kernel/arch/x86/crypto/blake2s-x86_64.ko
  SIGN    /lib/modules/5.14.0-rocky9_5_rebuild+/kernel/arch/x86/crypto/blake2s-x86_64.ko

[SNIP]

  SIGN    /lib/modules/5.14.0-rocky9_5_rebuild+/kernel/sound/xen/snd_xen_front.ko
  DEPMOD  /lib/modules/5.14.0-rocky9_5_rebuild+
[TIMER]{MODULES}: 40s
Making Install
sh ./arch/x86/boot/install.sh 5.14.0-rocky9_5_rebuild+ \
	arch/x86/boot/bzImage System.map "/boot"
[TIMER]{INSTALL}: 44s
Checking kABI
kABI check passed
Setting Default Kernel to /boot/vmlinuz-5.14.0-rocky9_5_rebuild+ and Index to 2
The default is /boot/loader/entries/b8e2f4fa81d64e9da6b2fb2793b7d940-5.14.0-rocky9_5_rebuild+.conf with index 2 and kernel /boot/vmlinuz-5.14.0-rocky9_5_rebuild+
The default is /boot/loader/entries/b8e2f4fa81d64e9da6b2fb2793b7d940-5.14.0-rocky9_5_rebuild+.conf with index 2 and kernel /boot/vmlinuz-5.14.0-rocky9_5_rebuild+
Generating grub configuration file ...
Adding boot menu entry for UEFI Firmware Settings ...
done
Hopefully Grub2.0 took everything ... rebooting after time metrices
[TIMER]{MRPROPER}: 8s
[TIMER]{BUILD}: 1642s
[TIMER]{MODULES}: 40s
[TIMER]{INSTALL}: 44s
[TIMER]{TOTAL} 1739s
Rebooting in 10 seconds
```

```
Last login: Thu Dec 19 15:14:22 2024 from 192.168.122.1
[maple@r9-sigcloud-builder ~]$ uname -a
Linux r9-sigcloud-builder 5.14.0-rocky9_5_rebuild+ #1 SMP PREEMPT_DYNAMIC Thu Dec 19 15:14:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### CODE REVIEW

**Review by gvrose8192 — APPROVED** [review]
LGTM - Thanks!

**Comment by bmastbergen** [comment]
Just did a quick spot check of a handful of these 'changes not in upstream' and they are actually in upstream but are very new.  Maybe you needed to do a fetch of the latest upstream first?  I don't know that we care that much either

**Comment by PlaidCat** [comment]
> Just did a quick spot check of a handful of these 'changes not in upstream' and they are actually in upstream but are very new. Maybe you needed to do a fetch of the latest upstream first? I don't know that we care that much either

Good catch ... yes i didn't do a fetch but I think its because I have a caching mechanism for this process so I don't need to recreate all of the structure for the `5.14..MASTER:HEAD`
I deteled the cache, fetching and rerunning th build

**Comment by gvrose8192** [comment]
Let me run another compile check before I re-approve.  Thanks Brett and Maple!

**Review by bmastbergen — APPROVED** [review]
`
Number of commits matched with upstream: 39 (92.86%)
`

Now we're talking!  :curling_stone:

**Comment by gvrose8192** [comment]
> `Number of commits matched with upstream: 39 (92.86%)`
> 
> Now we're talking! 🥌

Brett, it's great having more eyes on this stuff, Thanks!!!!!

**Review by gvrose8192 — APPROVED** [review]
Even better this round, Thanks Brett!

**Comment by PlaidCat** [comment]
:table flip:

I keep forgetting that when you do `rebase and merge` like we did for this: https://github.com/ctrliq/kernel-src-tree/pull/30 will cause a rewrite of the the sha so if you branched say `rocky9_5_rebuild` off of the local version you'll have divergent git histories.

So I ended up after a buch of git screaming about how I can't do `--ff-only` I deleted  the local `rocky9_5` and rechecked it out, did  a `rebase` of `rocky9_5_rebuidl` and then a `git merge --ff-only rocky9_5_rebuild` onto `rocky9_5` and push to origin

This was a mistake because now this PR has differnt SHAs due to the rebase, so now I have a bypass violation and this PR doesn't match up.

@github really needs to fix this (we don't support `--ff-only` merging) I still cannot believe that both `bitbucket` and `gitlab` support this but github can't seem to figure this one out. /rant

**Pull request closed without merging**
